#! /bin/bash
#
# Check the status of integrit
# Written by Kevin MET https://mnt-tech.fr/
# Created: 07-10-2013
# Last Modified: 07-10-2013
# 
# Usage: ./check_integrit -C /path/to/intergrit.conf -P /usr/sbin/integrit
#
# 1.0 First Release
#set -x

# Constant
PROGNAME=`/usr/bin/basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION="1.0"

# States
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

# Default
exitstatus=$STATE_WARNING 
config='/etc/integrit/integrit.conf'
INTEGRIT='/usr/sbin/integrit'

print_usage() {
	echo "Usage: $PROGNAME -C /etc/integrit/integrit.conf -P /usr/sbin/integrit"
	echo "Usage: $PROGNAME --help"
	echo "Usage: $PROGNAME --version"
}

print_revision() {
        echo "$1 v$2 (nagios-plugins 1.4.16)"
        echo -e "This nagios plugins come with ABSOLUTELY NO WARRANTY. You may redistribute\ncopies of the plugins under the terms of the GNU General Public License.\n"
}

print_help() {
	print_revision $PROGNAME $REVISION
	echo ""
	print_usage
	echo ""
	echo "Check integrit status plugin for Nagios"
}

while test -n "$1"; do
    case "$1" in
        --help)
            print_help
            exit $STATE_OK
            ;;
        -h)
            print_help
            exit $STATE_OK
            ;;
        --version)
            print_revision $PROGNAME $REVISION
            exit $STATE_OK
            ;;
        -V)
            print_revision $PROGNAME $REVISION
            exit $STATE_OK
            ;;
        --config)
            config=$2
            shift
            ;;
        -C)
           config=$2
            shift
            ;;
	-P)
	    INTEGRIT=$2
	    shift
	    ;;
	--path)
	    INTEGRIT=$2
	    shift
	    ;;
        -x)
            exitstatus=$2
            shift
            ;;
        --exitstatus)
            exitstatus=$2
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            print_usage
            exit $STATE_UNKNOWN
            ;;
    esac
    shift
done

# If the config file doesn't exist, exit
if [ ! -e $config ]
then
	echo "Configuration file: $config does not exist!\n"
	exit $STATE_UNKNOWN
elif [ ! -r $logfile ]
then
	echo "Configuration file: $config is not readable!\n"
	exit $STATE_UNKNOWN
else
	sudo $INTEGRIT -C $config -cu > /tmp/integrit-$$ 2>/dev/null
	case $? in
		0)
		echo "Check integrit: OK"
		exit $STATE_OK
		rm /tmp/integrit-$$
		;;
		2)
		echo "CRITICAL: Integrit fails to do its job"
		exit $STATE_CRITICAL
		rm /tmp/integrit-$$
		;;
		1)
		echo "CRITICAL check /tmp/integrit-$$ to see the last failed report"
		while read line
		do
			echo -e "CRITICAL :$line\n" | grep ":changed:\|:missing:\|:new:"
		done</tmp/integrit-$$
		exit $STATE_CRITICAL
		;;
		*)
		echo "CRITICAL: Integrit fails to do its job"
		exit $STATE_CRITICAL
		rm /tmp/integrit-$$
		;;
	esac
fi

